export const themes = {
    light: {
        colors: {
            primary: "#fb9678",
            "on-primary": "#fff",
            secondary: "#03c9d7",
            "on-secondary": "#fff",
            info: "#539BFF",
            "on-info": "#fff",
            success: "#05b187",
            "on-success": "#fff",
            accent: "#FFAB91",
            "on-accent": "#fff",
            warning: "#fec90f",
            "on-warning": "#fff",
            error: "#fb9678",
            "on-error": "#fff",
            textSecondary: "#000",

            //backGround
            background: "#f6f6f6",
            "on-background": "#000",
            surface: "#fff",
            "on-surface": "#000",

            "grey-50": "#FAFAFA",
            "grey-100": "#F5F5F5",
            "grey-200": "#EEEEEE",
            "grey-300": "#E0E0E0",
            "grey-400": "#BDBDBD",
            "grey-500": "#9E9E9E",
            "grey-600": "#757575",
            "grey-700": "#616161",
            "grey-800": "#424242",
            "grey-900": "#212121",
        },
        variables: {
            "code-color": "#d400ff",
            "overlay-scrim-background": "#2E263D",
            "tooltip-background": "#1A0E33",
            "overlay-scrim-opacity": 0.5,
            "hover-opacity": 0.04,
            "focus-opacity": 0.1,
            "selected-opacity": 0.08,
            "activated-opacity": 0.16,
            "pressed-opacity": 0.14,
            "dragged-opacity": 0.1,
            "disabled-opacity": 0.4,
            "border-color": "#2E263D",
            "border-opacity": 0.12,
            "table-header-color": "#F6F7FB",
            "high-emphasis-opacity": 0.9,
            "medium-emphasis-opacity": 0.7,

            // 👉 shadows
            "shadow-key-umbra-color": "#2E263D",
            "shadow-xs-opacity": "0.16",
            "shadow-sm-opacity": "0.18",
            "shadow-md-opacity": "0.20",
            "shadow-lg-opacity": "0.22",
            "shadow-xl-opacity": "0.24",
        },
    },
    dark: {
        colors: {
            primary: "#fb9678",
            "on-primary": "#fff",
            secondary: "#03c9d7",
            "on-secondary": "#fff",
            info: "#539BFF",
            "on-info": "#fff",
            success: "#13DEB9",
            "on-success": "#fff",
            accent: "#FA896B",
            "on-accent": "#fff",
            warning: "#FFAE1F",
            "on-warning": "#fff",
            error: "#FA896B",
            "on-error": "#fff",
            textSecondary: "#fff",

            //backGround
            background: "#171c23",
            "on-background": "#fff",
            // surface: "#312d4b",
            surface: "#1a2027",
            "on-surface": "#fff",

            "grey-50": "#2A2E42",
            "grey-100": "#2F3349",
            "grey-200": "#4A5072",
            "grey-300": "#5E6692",
            "grey-400": "#7983BB",
            "grey-500": "#8692D0",
            "grey-600": "#AAB3DE",
            "grey-700": "#B6BEE3",
            "grey-800": "#CFD3EC",
            "grey-900": "#E7E9F6",
        },
        variables: {
            "code-color": "#d400ff",
            "overlay-scrim-background": "#312D4B",
            "tooltip-background": "#F7F4FF",
            "overlay-scrim-opacity": 0.5,
            "hover-opacity": 0.04,
            "focus-opacity": 0.1,
            "selected-opacity": 0.08,
            "activated-opacity": 0.16,
            "pressed-opacity": 0.14,
            "disabled-opacity": 0.4,
            "dragged-opacity": 0.1,
            "border-color": "#E7E3FC",
            "border-opacity": 0.12,
            "table-header-color": "#3D3759",
            "high-emphasis-opacity": 0.9,
            "medium-emphasis-opacity": 0.7,

            // 👉 Shadows
            "shadow-key-umbra-color": "#131120",
            "shadow-xs-opacity": "0.20",
            "shadow-sm-opacity": "0.22",
            "shadow-md-opacity": "0.24",
            "shadow-lg-opacity": "0.26",
            "shadow-xl-opacity": "0.28",
        },
    },
};
export default themes;
